# Generated by Django 5.0.6 on 2024-06-24 23:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Government',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('start_year', models.IntegerField()),
                ('end_year', models.IntegerField()),
                ('color1', models.CharField(max_length=7)),
                ('color2', models.CharField(max_length=7)),
                ('color3', models.CharField(max_length=7)),
                ('color4', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
                ('img', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=7)),
                ('year', models.IntegerField()),
                ('version', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('filename', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('title', models.CharField(max_length=255)),
                ('fixed_result', models.IntegerField()),
                ('visible', models.BooleanField()),
                ('in_landing', models.BooleanField()),
                ('government', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.government')),
            ],
        ),
    ]
