# Generated by Django 5.0.6 on 2024-07-02 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_area_phase_priority_bill_promise_justification'),
    ]

    operations = [
        migrations.AddField(
            model_name='government',
            name='extra_info',
            field=models.TextField(null=True),
        ),
    ]
