# Generated by Django 5.0.6 on 2024-07-02 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_government_extra_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='in_landing_2',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='study',
            name='in_landing',
            field=models.BooleanField(default=False),
        ),
    ]
