# Generated by Django 5.0.6 on 2024-07-05 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_study_in_landing_2_alter_study_in_landing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='priority',
            name='count',
        ),
        migrations.AddField(
            model_name='priority',
            name='countColumnName',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
