# Generated by Django 5.0.6 on 2024-07-05 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_remove_priority_count_priority_countcolumnname'),
    ]

    operations = [
        migrations.AddField(
            model_name='justification',
            name='justification',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='priority',
            field=models.JSONField(null=True),
        ),
    ]
