# Generated by Django 5.0.6 on 2024-07-05 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_justification_justification_alter_bill_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='chekIsEmpty',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='url',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='government',
            name='color1',
            field=models.CharField(max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='government',
            name='color2',
            field=models.CharField(max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='government',
            name='color3',
            field=models.CharField(max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='government',
            name='color4',
            field=models.CharField(max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='government',
            name='end_year',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='government',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='government',
            name='start_year',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='phase',
            name='fullfilment',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='phase',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='priority',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='promise',
            name='content',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='promise',
            name='ja_why',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='promise',
            name='number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='promise',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='study',
            name='color',
            field=models.CharField(max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='study',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='study',
            name='filename',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='study',
            name='fixed_result',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='study',
            name='img',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='study',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='study',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='study',
            name='type',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='study',
            name='version',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='study',
            name='visible',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='study',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
