# Generated by Django 5.0.6 on 2024-07-16 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_alter_area_name_alter_bill_chekisempty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='justification_summary',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='promise',
            name='coherence_level',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='promise',
            name='jc_why',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='phase',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.phase'),
        ),
        migrations.AlterField(
            model_name='study',
            name='in_landing',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='study',
            name='in_landing_2',
            field=models.BooleanField(default=True),
        ),
    ]
