# Generated by Django 5.0.6 on 2024-07-16 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_bill_justification_summary_promise_coherence_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promise',
            name='content',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
