# Generated by Django 5.0.6 on 2024-07-16 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_alter_promise_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='title',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='promise',
            name='content',
            field=models.TextField(null=True),
        ),
    ]
