# Generated by Django 5.0.6 on 2024-07-29 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_alter_bill_id_alter_promise_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='justification_summary',
            field=models.TextField(null=True),
        ),
    ]
