# Generated by Django 5.0.6 on 2024-07-29 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_alter_bill_justification_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='justification',
            name='justification',
            field=models.TextField(null=True),
        ),
    ]
