# Generated by Django 5.0.6 on 2024-07-29 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_alter_justification_justification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='justification',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='justification',
            name='justification',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
