# Generated by Django 5.0.6 on 2024-07-29 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_alter_justification_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='justification',
            name='justification',
            field=models.TextField(null=True),
        ),
    ]
